// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhpqJpVluC8qEyaO_Mpo51UeSLsGl2y7M',
    appId: '1:641553643711:web:98ecacf285eeb9ace06e0a',
    messagingSenderId: '641553643711',
    projectId: 'loginsignupapp-dabb9',
    authDomain: 'loginsignupapp-dabb9.firebaseapp.com',
    storageBucket: 'loginsignupapp-dabb9.appspot.com',
    measurementId: 'G-HRRL55DZT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2tuyJH_PwNzl_d67j8l88Byr8jO_xIh4',
    appId: '1:641553643711:android:2b3794d6d02f25a5e06e0a',
    messagingSenderId: '641553643711',
    projectId: 'loginsignupapp-dabb9',
    storageBucket: 'loginsignupapp-dabb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2F-rqG2v0tjCZb4Ip8xODR-C-0QaZL0',
    appId: '1:641553643711:ios:ccdc03f00bf0cc7de06e0a',
    messagingSenderId: '641553643711',
    projectId: 'loginsignupapp-dabb9',
    storageBucket: 'loginsignupapp-dabb9.appspot.com',
    iosClientId: '641553643711-d3ph7mot1tvjoob5brb0orto13df58dc.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicLoginSignupFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2F-rqG2v0tjCZb4Ip8xODR-C-0QaZL0',
    appId: '1:641553643711:ios:ccdc03f00bf0cc7de06e0a',
    messagingSenderId: '641553643711',
    projectId: 'loginsignupapp-dabb9',
    storageBucket: 'loginsignupapp-dabb9.appspot.com',
    iosClientId: '641553643711-d3ph7mot1tvjoob5brb0orto13df58dc.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicLoginSignupFirebase',
  );
}
